### PR TITLE
[AvoidAdditionalProperties] Add null check before dereferencing "@.additionalProperties"

### LINKED ISSUE #680: LintDiff: FATAL: TypeError: Cannot read properties of null (reading 'additionalProperties')
Context on [Teams](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1714007148259?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1713981617002&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1714007148259).

- https://github.com/Azure/azure-rest-api-specs-pr/pull/18022

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3729857&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7

Raw log:
- https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/3729857/logs/451

> 2024-04-24T18:13:49.4556642Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"spectralPluginFunc: Validating OpenAPI spec. TypeSpec-generated: false. Path: 'file:///mnt/vss/_work/1/lint-c93b354fd9c14905bb574a8834c4d69b/specification/network/resource-manager/Microsoft.Network/stable/2023-11-01/applicationGateway.json'"}
>
> 2024-04-24T18:13:49.4557616Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"fatal","message":"spectralPluginFunc: Failed validating: 'file:///mnt/vss/_work/1/lint-c93b354fd9c14905bb574a8834c4d69b/specification/network/resource-manager/Microsoft.Network/stable/2023-11-01/applicationGateway.json'. Errors encountered:\nTypeError: Cannot read properties of null (reading 'additionalProperties')"}

### PR DESCRIPTION
**Pull request by mikeharder**
- Fixes "TypeError: Cannot read properties of null (reading 'additionalProperties')"
- Fixes #680

### CODE REVIEW

File: packages/rulesets/generated/spectral/az-arm.js [hunk 1]
```diff
@@ -3160,7 +3160,7 @@ const ruleset = {
             disableForTypeSpecReason: "Covered by TSP's '@azure-tools/typespec-azure-resource-manager/no-record' rule.",
             resolved: true,
             formats: [oas2],
-            given: "$.definitions..[?(@property !== 'tags' && @property !== 'delegatedResources' && @property !== 'userAssignedIdentities' && @.additionalProperties)]",
+            given: "$.definitions..[?(@property !== 'tags' && @property !== 'delegatedResources' && @property !== 'userAssignedIdentities' && @ && @.additionalProperties)]",
```
Comment (mikeharder) [inline packages/rulesets/generated/spectral/az-arm.js:3163]: Something in `specification/network/resource-manager/Microsoft.Network/stable/2023-11-01` causes `@` to be null in this expression, which leads to this error:

```
TypeError: Cannot read properties of null (reading 'additionalProperties')
```

#680

**Review by konrad-jamrozik — APPROVED** [review]

**Comment by konrad-jamrozik** [comment]
This works around known issue in json-plus used by spectral, used by this repo:

- https://github.com/stoplightio/spectral/issues/1920
